server:
  port: 8081
  servlet:
    context-path: /api


logging:
  level:
    web: DEBUG


app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/amigoscodedemo
    username: postgres
    password: password
    pool-size: 30     # Allowed number of given connections at any given time.

