# Port : 5000 is the port number for AWS Elastic Beanstalk
server:
  port: 5000


logging:
  level:
    web: DEBUG


app:
  datasource:
    # 'localhost' was replaced by the 'Endpoint' of our AWS Database
    jdbc-url: jdbc:postgresql://fullstackstudentregistrydb.cuukxtoir1hy.us-east-1.rds.amazonaws.com:5433/amigoscodedemo
    username: paomanspostgresql
    password: paomanspostgresql
    pool-size: 30     # Allowed number of given connections at any given time.

